# Generated by Django 2.1.4 on 2018-12-25 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20181225_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='iden',
            new_name='identity',
        ),
    ]
