# Generated by Django 2.1.4 on 2018-12-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
    ]
