# Generated by Django 2.1.4 on 2018-12-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_land'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
