# Generated by Django 2.1.4 on 2018-12-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20181226_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
