# Generated by Django 2.1.4 on 2018-12-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20181226_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='lot',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
