# Generated by Django 2.1.4 on 2018-12-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20181226_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('product_name', models.CharField(max_length=32)),
                ('purchase_number', models.DecimalField(decimal_places=2, max_digits=5)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remark', models.CharField(max_length=32)),
            ],
        ),
    ]
