# Generated by Django 2.1.4 on 2018-12-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20181226_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_date',
            field=models.DateTimeField(),
        ),
    ]
