# Generated by Django 2.1.4 on 2018-12-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20181227_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_number',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
