# Generated by Django 2.1.4 on 2018-12-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20181227_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='remark',
            field=models.CharField(default='无', max_length=20),
        ),
    ]
