# Generated by Django 2.1.4 on 2018-12-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20181227_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_date',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='remark',
            field=models.CharField(default='无', max_length=32),
        ),
    ]
