# Generated by Django 2.1.4 on 2018-12-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_auto_20181227_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.CharField(max_length=10),
        ),
    ]
