# Generated by Django 2.1.4 on 2018-12-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_auto_20181227_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage_date', models.CharField(max_length=15)),
                ('muck_name', models.CharField(max_length=10)),
                ('tlc', models.CharField(max_length=10)),
                ('twlr', models.CharField(max_length=10)),
                ('naworm', models.CharField(default='无', max_length=32)),
            ],
        ),
    ]
