# Generated by Django 2.1.4 on 2018-12-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_dosage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosage',
            name='tlc',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
