# Generated by Django 2.1.4 on 2018-12-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_croprecords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recovery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recovery_date', models.CharField(max_length=15)),
                ('vegetables_name', models.CharField(max_length=10)),
                ('recovery_number', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
    ]
